export default ({
  Users,

  Cites,
  Regions,
  Sports,

  Groups,
  GroupRoles,
  GroupMembers,

  Events,
  EventMembers,
}) => {
  // GENERATED BY SEQUELIZE AUTO

  Regions.belongsTo(Cites, { as: "city", foreignKey: "cityId" });
  Cites.hasMany(Regions, { as: "Regions", foreignKey: "cityId" });
  EventMembers.belongsTo(Events, { as: "event", foreignKey: "eventId" });
  Events.hasMany(EventMembers, { as: "EventMembers", foreignKey: "eventId" });
  GroupMembers.belongsTo(GroupRoles, {
    as: "groupRole",
    foreignKey: "groupRoleId",
  });
  GroupRoles.hasMany(GroupMembers, {
    as: "GroupMembers",
    foreignKey: "groupRoleId",
  });
  Events.belongsTo(Groups, { as: "group", foreignKey: "groupId" });
  Groups.hasMany(Events, { as: "Events", foreignKey: "groupId" });
  GroupMembers.belongsTo(Groups, { as: "group", foreignKey: "groupId" });
  Groups.hasMany(GroupMembers, { as: "GroupMembers", foreignKey: "groupId" });
  Events.belongsTo(Sports, { as: "activity_Sport", foreignKey: "activity" });
  Sports.hasMany(Events, { as: "Events", foreignKey: "activity" });
  EventMembers.belongsTo(Users, { as: "user", foreignKey: "userId" });
  Users.hasMany(EventMembers, { as: "EventMembers", foreignKey: "userId" });
  GroupMembers.belongsTo(Users, { as: "user", foreignKey: "userId" });
  Users.hasMany(GroupMembers, { as: "GroupMembers", foreignKey: "userId" });
};
