export default ({ Cites, Regions }) => {
  // GENERATED BY SEQUELIZE AUTO

  Regions.belongsTo(Cites, { as: "city", foreignKey: "cityId" });
  Cites.hasMany(Regions, { as: "Regions", foreignKey: "cityId" });
};
